- src/simplebar.css
Adds IE8 fall backs for Opacity.
Ref: #15
> :bug: fix: IE8 opacity fall back

- demo/index.html
- src/simplebar.css
- src/simplebar.js
Simple boolean fix for issue #67
> Fix for #67 forceEnabled

- README.md
Hi Adrien,
I just published a Ruby gem for easier use of SimpleBar with Ruby on Rails: https://rubygems.org/gems/simplebar-rails
Would be cool to add it here to the README.
Awesome job with SimpleBar btw, I really like it :+1:
> Add info about new simplebar-rails gem

- src/simplebar.js
I think `trailing` should be true and `leading` could be either?
Let me know how you think :D
This would also close #128.
> Change recalculate debounce trailing to true

- packages/simplebar/src/simplebar.js
> Add 'visible', 'horizontal' and 'vertical' classnames to options

- index.html
This just fixes a minor inconsistency in your gh-page design, but it was bothering me for a while already #ocd :grimacing:
> Fix spelling and add an icon to GitHub link

- packages/simplebar-react/__snapshots__/index.test.js.snap
- packages/simplebar-react/index.js
- packages/simplebar-vue/__snapshots__/index.test.js.snap
- packages/simplebar-vue/index.vue
Had some free time to update the vue/react components. Unit tests all seem to pass testing. :)
> Updated vue/react packages & associated unit tests.

- packages/simplebar/src/simplebar.js
> Hide scrollbars with display instead of visibility

- packages/simplebar/src/simplebar.css
> Disable margin collapsing on .simplebar-resize-wrapper

- packages/simplebar/src/simplebar.css
> Remove unexpected width: inherit and related rules on [data-simplebar]

- packages/simplebar/src/simplebar.js
- packages/simplebar/test/simplebar.test.js
> Make getScrollElement return the scroll element again

- packages/simplebar-react/package.json
- packages/simplebar-vue/package.json
- packages/simplebar/package.json
Documentation: https://docs.npmjs.com/files/package.json#repository.
> package.json: Add repository.directory

- packages/simplebar-vue/.babelrc
- packages/simplebar-vue/__snapshots__/index.test.js.snap
- packages/simplebar-vue/index.test.js
- packages/simplebar-vue/jest-unit.config.js
- packages/simplebar-vue/package.json
- yarn.lock
> Include core-js package in package.json

- packages/simplebar-react/simplebar-react.d.ts
Added type definitions to "autoHide" and "forceVisible" to fix erros on use it on typescript projects
> Add type definitions to fix typescript project

- packages/simplebar/src/simplebar.js
Makes the speed of "autoscroll" when clicking on the track customizable.
Sorry I couldn't test this (writing this blindly) - the instructions for building are unclear (`rollup.config.js` is missing)
> feat: add clickOnTrackSpeed option

- packages/simplebar/src/scrollbar-width.js
- packages/simplebar/src/simplebar.js
> Fix scrollbar width calculation for iframe

- packages/simplebar/package.json
- packages/simplebar/src/simplebar.js
- yarn.lock
Not sure if I did the removing/installing of the dependencies correctly, haven't used yarn/lerna much. If something is wrong, let me know!
> Replace unmaintained resize-observer-polyfill with @juggle/resize-observer

- packages/simplebar-vue/index.vue
Fixes: https://github.com/Grsmto/simplebar/issues/463
The diff is a bit dirty because of changes in formatting, but the only change here is [this line](https://github.com/Grsmto/simplebar/pull/569/commits/01a16dd1c054ad194df5655333e8cacfb199c7d3#diff-7e4e382411057f3e38db44a6b8eebedd5b8699c6a683b1f1b353b659d3b4737fR12).
> [Vue package] Feature: ability to handle scroll listener

- packages/simplebar-react/index.js
- packages/simplebar-react/simplebar-react.d.ts
fixes https://github.com/Grsmto/simplebar/issues/606
> feat: Add tag props into React Simplebar component

- packages/simplebar/src/simplebar.js
> Fix for "Error: ResizeObserver loop limit exceeded"
