Grsmto/simplebar

src/simplebar.js

I was getting the following error after transpiling from ES6 with babel:
`ReferenceError: assignment to undeclared variable SCROLLBAR_WIDTH`

Declare SCROLLBAR_WIDTH variable for strict mode

---

src/simplebar.js

Would you accept this patch? It enables module loader support, so that you can load the plugin via AMD or CommonJS require() statements without having to pre-load jQuery into the global environment.

Module loader compatibility

---

src/simplebar.js

Sorry to bother you again. It turns out that the AMD-style loading was broken. Sorry about that, I should have tested it before submitting the patch.
I have removed it and tidied up the CommonJS environment detection using the recommendation from the npm blog:
http://blog.npmjs.org/post/112712169830/making-your-jquery-plugin-work-better-with-npm

Fix module loader detection

---

src/simplebar.js

Browser doesn't show scrollbars on a small div with overflow visible, mistakenly thinking it has "floating" scrollbars. (https://github.com/Grsmto/simplebar/issues/16)

Firefox on Linux falsely detects "floating" scrollbars

---

src/simplebar.js

Changed the condition where recalculate was being called on the MutationObserver. It will recalculate when any child of "this.el" has been mutated. I noticed this issue when I had an accordion in the content area. The children of the content area were mutating, but not the element itself. I didn't see any visual performance degradation with this change, but it could be argued this adds some unnecessary overhead. It did fix my issue though.
I'd be happy to create a plunkr if you would like an example.

Recalculate when child node has been mutated

---

README.md

I troubleshooted this for a while before I finally figured it out. 
The css file in question is stored in 'simplebar/dist/simplebar.css', not 'simplebar/src/simplebar.css'.
Hopefully this will save someone else a lot of trouble later on.

Fixed error in file path

---

packages/simplebar/src/simplebar.js

See issue #238. Officially my first PR to GitHub, hopefully guide wasn't lying.

Fix 'visible' classname bug when using custom classnames

---

README.md
packages/simplebar-react/package.json
packages/simplebar-vue/package.json
packages/simplebar/package.json
packages/simplebar/src/simplebar.js

quick fix to recalculate simplebar when nodes are removed as well as added. 
useful when you have accordion component inside fixed container with simplebar.

recalculate when nodes are removed as well.

---

packages/simplebar-react/__snapshots__/index.test.js.snap
packages/simplebar-react/index.js
packages/simplebar-react/index.test.js

This allow usage with libraries that control scrolling like react-beautiful-dnd, which requires passing ref to scrollable container.

simplebar-react: Now supports passing props to scrollable node.

---

packages/simplebar/src/simplebar.js

A suggested fix to issue #282, utilising the existing ResizeObserver.
In order to correctly detect size changes in all content within the simplebar container, a wrapper element is added to contain the user content. Any time this any of this content changes size, the resizeWrapper does too and fires a corresponding resize event.

Added 'resize-wrapper' to enable detection of content resizes via ResizeObserver.

---

packages/simplebar/src/simplebar.js

A scrollbar drag continues even if the pointer moves off the scrollbar track while the mouse button is down.  We want to block other elements’ mousemove/mouseup handlers from firing during this period.

Set useCapture on document mousemove/mouseup handlers during drag

---

packages/simplebar/src/simplebar.js

Similarly to commit f7fbda9a43866a2404d20e5e0f50c55ce72add4c (#312), which suppressed mousemove/mouseup events, we want to block other elements’ click/dblclick handlers from firing at the end of a scrollbar drag.

Suppress click/dblclick events during drag

---

packages/simplebar-vue/__snapshots__/index.test.js.snap
packages/simplebar-vue/index.test.js
packages/simplebar-vue/index.vue

This pull request makes so `SimpleBar` is initialized when `simplebar-vue` component is mounted, adds ability to access `SimpleBar` instance and call `getScrollElement`, `getContentElement` and `recalculate` methods directly on `simplebar-vue` component instance.
This will simplify https://github.com/Grsmto/simplebar/issues/331#issuecomment-501284326:
- it will be possible to use `this.$refs.container.getScrollElement()` instead of `this.$refs.container.$el.SimpleBar.getScrollElement()`
- `SimpleBar` will be property initialized in `mounted` hook

Add methods to vue component

---

packages/simplebar-react/__snapshots__/index.test.js.snap
packages/simplebar-react/index.js

Since simplebar-content-wrapper now handles scrolling, scrollableNodeProps should be applied to simplebar-content-wrapper instead of simplebar-content

Fixes scrollableNodeProps

---

packages/simplebar/src/simplebar.js

`this.el.querySelector` returns wrong element if there is nested `.simplebar-track` exist. This cause issues with nested simplebars in some cases (e.g. simplebar-react which creates full dom tree including tracks). Searching for track element inside immediate children solves this issue.

Fix track elements selector

---

packages/simplebar/src/scrollbar-width.js
packages/simplebar/src/simplebar.css
packages/simplebar/src/simplebar.js

So I've been working on a new way to define the scrollbar `isOverflowing` state. Basically in some scenarios the scrollbar was showing when it wasn't necessary or the opposite, it wasn't showing.
The issue was basically with browsers that support floating scrollbars and have it activated (every modern browsers on mac for example and pretty much every mobile browsers).
On these browsers I'm now hiding the scrollbar in CSS. However there might be some browsers that support floating scrollbar (where the `scrollbarWidth() calculation returns `0`) but don't support hiding of the scrollbar in CSS? I'm not sure.
I summon @Demivan and @andersk to have a quick look and see if you see something obviously wrong here.

chore: rework isOverflowing calculation

---

packages/simplebar/src/scrollbar-width.js

Native scrollbar width should not change over the life of an application.
Cache this value to eliminate some forced reflows
See #205  and #371

Cache the scrollbar width for the life of the application

---

packages/simplebar/src/scrollbar-width.js

In scrollbar-width.js, the code was doing window.addEventListener even when window was undefined.
This broke simplebar in SSR environments.
This commits adds a check before trying to add the resize event.

fix: add window check before addEventListener

---

packages/simplebar-react/README.md

The inline comment was causing GitHub's syntax highlighter to grey out the closing tag `</SimpleBar>`:

Fix syntax highlighting in README

---

packages/simplebar/src/simplebar.css

The default overflow style on tablets (for example the Microsoft Surface) is"-ms-autohiding-scrollbar". That causes simplebar to miscalculate the sidebar size (width:0) and that causes the native scroll bar to remain visible.
You can easily see that by visiting the simplebar homepage on Microsoft Surface, using the Edge browser.

Set '-ms-overflow-style: scrollbar' on the scrollbar sizer element

---

packages/simplebar/demo/Demo.js
packages/simplebar/src/helpers.js
packages/simplebar/src/scrollbar-width.js
packages/simplebar/src/simplebar.js

Addresses #394 -- where possible replaces `window` and `document` globals with `el.ownerDocument.defaultView` and `el.ownerDocument`, respectively. This gives more flexibility to the library, for example letting you render a `SimpleBar` on an element inside an `iframe`, from some JavaScript running in the document containing the `iframe`.

Remove some window/document globals

---

packages/simplebar-react/index.js

should ignore data-simplebar-direction when checking for deprecation, it required in css to make rtl work.

fix rtl in react

---

packages/simplebar/src/simplebar.js

I'm using SSR with Angular 7, and after I have added simplebar for angular, on SSR I'm getting an error:
`Error generating html for req /roadmap TypeError: Cannot read property 'removeEventListener' of undefined
at SimpleBar.removeListeners (...\dist\server.js:267875:27)
at SimpleBar.unMount (...\dist\server.js:267895:10)
at SimplebarAngularComponent.module.exports.SimplebarAngularComponent.ngOnDestroy (...\dist\server.js:267988:24)`
In the PR I have just added if checks for the existence of used vars. With this PR SSR works fine for me.
It's also reproducible on 2.2 and 3.0 versions of the plugin for Angular,

Fix angular SSR issues

---

packages/simplebar/simplebar.d.ts

Hi.
The types in this repository are not identical to the latest version of the types in DefinitelyTyped.
The missing fixes:
1. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43123
2. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51538
Thanks @nzacca and @breadadams!
I also want to deprecate types in DefinitelyTyped.

Apply types fixes from DefinitelyTyped

---

packages/simplebar-vue/index.vue

The previous problem was related to that if we will not pass any handler, Vue will try to use `undefined` as a function. It causes error messages in the browser's console.

[Vue package] Fix: exception about undefined scroll listener

---

packages/simplebar/src/index.js

An element that’s moved to a different position in the DOM (such as by the constructor of a containing SimpleBar) can show up as both removed and added in a mutation record, so we need to test whether the element is currently present.
Fixes #552.

fix: Check that added/removed nodes are still present/absent

---

packages/simplebar-react/tests/__snapshots__/index.test.js.snap
packages/simplebar-vue/tests/__snapshots__/index.test.js.snap
packages/simplebar/README.md
packages/simplebar/src/simplebar.js

It was impossible to scroll slider with keyboard in Chrome and Safari.
I added `tabindex="0"` to allow focusing on slider and `aria-label` for screen readers.
More info here https://marcus.io/blog/accessible-overflow

Added ability to scroll with keyboard

---

packages/simplebar/src/simplebar.css

fix: ensure native scrollbars are hidden on recent iOS versions

---

packages/simplebar-vue/package.json
yarn.lock

First I would like to apologise for breaking the `1.7.0` build :/  
I've trusted unit testing and [forgot to install it externally ](https://codesandbox.io/s/simplebar-1-7-0-0u4s8x) to ensure it works _in real life_, or should have asked you to release it as beta.
https://github.com/Grsmto/simplebar/blob/3c5cb8d4f9848f80e64b0196c438bb5b2243c68f/packages/simplebar-vue/utils.js#L1-L6
1. `vue-demi` is not only used for testing but also to dynamically create the lifecyle names map for cross-compatiblity with vue 2 and 3
1. updated `vue-demi` to latest version, I was going crazy to make the tests work and thought that vue-demi had something to do with it but I has not.

[simplebar-vue] fix: move vue-demi to dependencies

---

packages/simplebar-angular/src/lib/simplebar-angular.component.ts

fix for the issue described here: https://github.com/Grsmto/simplebar/issues/626
This PR runs SimpleBar outside of Angular, so events from it do not trigger change detection.

Fix to Angular change detection

---

packages/simplebar/README.md

Fix typo in README (simplebar/src/simplebar)

---

packages/simplebar-core/package.json
packages/simplebar/package.json

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package
Fixes this error:
```console
$ npm i simplebar
$ tsc --init
$ echo 'import SimpleBar from "simplebar"' > test.ts
$ tsc
test.ts:1:23 - error TS7016: Could not find a declaration file for module 'simplebar'. '/tmp/test/node_modules/simplebar/dist/index.cjs' implicitly has an 'any' type.
Try `npm i --save-dev @types/simplebar` if it exists or add a new declaration (.d.ts) file containing `declare module 'simplebar';`
1 import SimpleBar from "simplebar"
~~~~~~~~~~~
Found 1 error in test.ts:1
```

Add types field to package.json

---

packages/simplebar-core/src/index.ts

Should fix #659 issue.
When dragging vertical scrollbar handle, it moves in reverse position when wrapper is in RTL mode. It looks like handle movement is reversed in RTL mode both, for horizontal (which is how it should be) and for vertical scrollbar (which is undesired behavior, as RTL layout doesn't change vertical page layout). You can also see the example in comments for issue, mentioned above.
Add additional checks for dragging position: scroll handle movement is inverted when layout is RTL (older check) and only when moving X axis (new check)

fix(core): Fix vertical scrollbar dragging in rtl mode

---

examples/react/src/App.js
examples/vue-2.7/src/App.vue
examples/vue-3/src/App.vue
packages/simplebar-vue/README.md

demo code in packages/simplebar-vue not working because the styles are not correctly imported. Also, the link to vue-demo is not correct. Fixed these and some similar problems in examples.

fix(vue&react): fix some demo codes  in examples and README

---

packages/simplebar-core/src/index.ts

Hi,
Thanks for the library - it's really useful especially when Chrome removes support for `overflow: overlay`. 
Currently, whenever scrolling ends, the scrollbar is hidden. However, when the user is dragging the scrollbar and has not yet released the mouse, it is better to keep the scrollbar visible so the user can continue dragging - it is more consistent with how the scrollbar works on MacOS.
This PR adds a simple check if the user still drags the scrollbar before hiding it.

Do not hide scrollbar if the mouse is being dragged and not yet released.

---

packages/simplebar/src/index.ts

Without an annotation, TypeScript defaults to `WeakMap<object, any>`.
Effect on `simplebar/dist/index.d.ts`:
```diff
import SimpleBarCore from 'simplebar-core';
export default class SimpleBar extends SimpleBarCore {
static globalObserver: MutationObserver;
-    static instances: WeakMap<object, any>;
+    static instances: WeakMap<Node, SimpleBar>;
constructor(...args: ConstructorParameters<typeof SimpleBarCore>);
static initDOMLoadedElements(): void;
static removeObserver(): void;
initDOM(): void;
unMount(): void;
static initHtmlApi(): void;
static handleMutations(mutations: MutationRecord[]): void;
}
```

Correct `SimpleBar.instances` type

---

packages/simplebar-angular/src/lib/simplebar-angular.component.html
packages/simplebar-angular/src/lib/simplebar-angular.component.ts
packages/simplebar-core/src/index.ts
packages/simplebar-react/index.tsx
packages/simplebar-react/tests/__snapshots__/index.test.tsx.snap
packages/simplebar-react/tests/index.test.tsx
packages/simplebar-vue/component.ts
packages/simplebar-vue/simplebar-vue.d.ts
packages/simplebar-vue/tests/index.test.ts
packages/simplebar/README.md
packages/simplebar/src/index.ts

Thank you for this library!
After https://github.com/Grsmto/simplebar/pull/587, there had been many complaints about `tabIndex=0` breaking existing behaviour. This PR adds `tabIndex` as an option with it's default set to 0.
The second commit also adds the `ariaLabel` option to the README.

Add tabIndex as a configurable option.

---

packages/simplebar-core/can-use-dom.d.ts
packages/simplebar-core/package.json
packages/simplebar/can-use-dom.d.ts
packages/simplebar/package.json
yarn.lock

There are still some dependencies to clean up
- Removed unused `can-use-dom` dependency from simplebar
- Removed unused `lodash` dependency from simplebar-core
- Moved `@types/lodash-es` in simplebar-core to a dev dependency

Clean up unused dependencies

---

packages/simplebar-angular/src/lib/simplebar-angular.component.ts

It seems that setting `tabIndex` and `ariaLabel `doesn't work as expected in Angular. `tabIndex `and `ariaLabel `always have their default values. To resolve this, the assignment of `ariaLabel` and `tabIndex` should be moved inside the `ngOnInit` method, as the constructor is called before the component is fully initialized.
At that point, `this.options` is still an empty object, rather than the options passed from the outside via the `@Input` parameter.

fix(Angular): fixed applying custom tabIndex and ariaLabel

---

packages/simplebar-react/index.tsx

Hey! I'm wondering this hasn't been fixed before. It breaks `simplebar-react` when using custom `classNames`.

fix(react): horizontal & vertical classNames

---

packages/simplebar/package.json

Solves an issue when importing `SimpleBar` in a project using esm and tyepscript:
```
Could not find a declaration file for module 'simplebar'.
```
This is because the index.d.ts file cannot be used because it is not in the package exports.

Add types to exports
